- name: Create new VM with minimal options
- hosts: proxmox
  tasks:
    - name: Create new VM with minimal options
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: y7sd5rq2
        api_host: 192.168.1.100
        name: spynal
        clone: template
        node: pve
        vmid: 456
