---
- name: Applica gli aggiornamenti di Windows
  hosts: Windows  # Assicurati che il tuo inventario in AWX abbia un gruppo 'windows'
  gather_facts: false
  tasks:
    - name: Cerca, scarica e installa gli aggiornamenti di sicurezza e critici
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
      register: update_results

    - name: Stampa i risultati dell'aggiornamento
      debug:
        var: update_results

   # --- Sezione Installazione Chocolatey ---
    - name: Verifica se Chocolatey è già installato
      ansible.windows.win_stat:
        path: C:\ProgramData\chocolatey\bin\choco.exe
      register: chocolatey_check

    - name: Installa Chocolatey (se non presente)
      ansible.windows.win_powershell:
        script: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; 
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      when: not chocolatey_check.stat.exists
      args:
        creates: C:\ProgramData\chocolatey\bin\choco.exe        

    # - name: Riavvio forzato del server
    #   ansible.windows.win_reboot:
