---
- name: Applica gli aggiornamenti di Windows
  hosts: Windows  # Assicurati che il tuo inventario in AWX abbia un gruppo 'windows'
  gather_facts: false
  tasks:
    - name: Cerca, scarica e installa gli aggiornamenti di sicurezza e critici
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
      register: update_results

    - name: Stampa i risultati dell'aggiornamento
      debug:
        var: update_results

    - name: Riavvio forzato del server
      ansible.windows.win_reboot:
